GET http://localhost:8081/places?text=quintas do godoy, betim

###
GET http://localhost:8081/places?text=jardim dos ipes, itabira, mg

###
@originId = ChIJAX9inSHDpgARY5Z6mPkV2l0

@destinationId = ChIJKa2IbhyhpQARSjjZ7plYtgA

###
GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}

###

POST http://localhost:8081/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}",
}

###
GET http://localhost:8081/routes

###

GET http://localhost:8081/routes/1
